### ISSUE TITLE
Crash with Jetpack Compose Alpha07 

### ISSUE THREAD

**Issue by johnnycube** [zsoltk/compose-router#46] opened 2020-11-13 15:48 UTC
Version of Jetpack Compose: alpha07
Version of Compose router: 0.21.0

The following runtime error is thrown

```
 java.lang.NoSuchFieldError: No field Companion of type Landroidx/compose/runtime/SlotTable$Companion; in class Landroidx/compose/runtime/SlotTable; or its superclasses (declaration of 'androidx.compose.runtime.SlotTable' appears in /data/data/com.metamythlabs.theseries/code_cache/.overlay/base.apk/classes.dex)
        at com.github.zsoltk.compose.router.RouterKt.Router(Router.kt:105)
        at com.metamythlabs.theseries.screens.MainRouter$Companion.Content(MainRouter.kt:28)
```

Usage of router (excerpt)

```
 companion object {
        @Composable
        fun Content(defaultRouting: Routing = Routing.Home) {
            Router("Main", defaultRouting) { backStack ->

                Providers(
                    AppNavigatorAmbient provides TheSeenNavigator(backStack)
                ) {
                    when (val routing = backStack.last()) {
                        is Routing.Home -> HomeRouter.Content()
                        is Routing.MoviesDetail -> MovieRouter.Content(movieId = routing.movieId)
                        is Routing.SeriesDetail -> SeriesRouter.Content(seriesId = routing.seriesId)
                        is Routing.UniverseDetail -> UniverseRouter.Content(universeId = routing.universeId)
                    }
                }
            }
        }
    }
}
```

Sadly I couldn't solve it quickly, hence I wanna report it.

**Comment by CaelumF** [comment] 2020-11-14 16:53
I'm getting this too

I tried cloning and updating to alpha07 and I can get it to compile, but when navigation changes I am seeing TableSlot errors.

Maybe we should be using https://developer.android.com/jetpack/compose/navigation nowadays anyway?

**Comment by zsoltk** [comment] 2020-11-16 09:58
Hello @johnnycube @CaelumF !

I've updated the library for alpha07 in #47 and released as 0.22.0. I couldn't reproduce the errors you reported – the sample apps work just fine with the same looking code. 

Note that they've rewritten the slot table impl, so you might need a clean rebuild cycle for the errors to go away. Please let me know how it goes.

**Comment by johnnycube** [comment] 2020-11-17 15:59
I can confirm that updating the library and rebuilding the project is working. I cannot comment on what did the trick though.

**Comment by CaelumF** [comment] 2020-11-17 22:11
I am pretty sure that the error originally in this issue is just because compose-router was using an older compose, and the issue I was getting was actually a separate alpha07 issue involving onClick that I haven't narrowed down yet. 

Nice one @zsoltk ! FYI I looked deeper into using compose-navigation and it seems a lot more complicated than this is (and currently android-specific) so thanks again for providing this :) 

@johnnycube no need to keep the issue open on my behalf anymore if there's nothing else outstanding

**Closed as completed** 2021-02-22 08:10 UTC
